name: Build and Lint

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build production
        run: npm run build
        env:
          NODE_ENV: production

  check-before-lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check if code changes are appropriate for linting
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.js$'; then
            echo "Code changes are appropriate for linting."
          else
            echo "No JavaScript files were changed. Skipping linting."
            exit 0
          fi

  lint:
    runs-on: ubuntu-latest
    needs: check-before-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run lint -- --fix
